### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by elmetal** [heart-of-swift/heart-of-swift.github.io#1]
On this page

https://github.com/heart-of-swift/heart-of-swift.github.io/blob/master/value-semantics/problems-without-value-semantics.md#value-semantics-を持たない型が起こしがちな問題

`Value Semantics_ を持たない型`

Should be:
`_Value Semantics_ を持たない型`

**Comment by koher** [comment]
ありがとうございます。直します。

**Comment by koher** [comment]
直しました！

**Comment by elmetal** [comment]
ありがとうございます！
