### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by elmetal** [heart-of-swift/heart-of-swift.github.io#2]
On this page
https://github.com/heart-of-swift/heart-of-swift.github.io/blob/master/value-semantics/index.md#value-semantics-を持つ例

Foo は 値型 なので a.value を変更しても b.value されません。

Should be:
Foo は 値型 なので a.value を変更しても b.value は変更されません。

**Comment by koher** [comment]
遅くなってすみません。ご指摘ありがとうございます！
